Ticket648 add ioc cp2800
ISISComputingGroup/EPICS-Cp2800 pull request #1
Opened 2019-06-03 10:09 UTC by LiamPanchaud

2019-06-14 10:56 UTC, Alistair-McGann-Tessella requested changes

2019-06-14 10:56 UTC, Alistair-McGann-Tessella commented on cp2800Sup/cp2800.db
> +    field(TWST, "Invallid Cmd")
Nit: spelling error

2019-06-14 10:56 UTC, Alistair-McGann-Tessella commented on cp2800Sup/cp2800.db
> +######### FOR FUTURE USE
Now there is a commit with these records for future use in, they no longer need to be on this branch as comments. They can be deleted safely, and can be refered to later at this commit

2019-06-14 10:56 UTC, Alistair-McGann-Tessella commented on cp2800Sup/cp2800.proto
> +#test { out "%s"; in "%40c"; }
Are these still used?

2019-06-14 10:56 UTC, Alistair-McGann-Tessella commented on cp2800Sup/cp2800.proto
> +# temp_0   { out $CP_CMD $TEMP_0   "%01<sum8>%1!"; in "%1!" $CP_RSP $TEMP_0   "%4r%01<sum8>"; wait $DLY; }
Are these protocols  parked to be used in the future too? If this is the case, I would recommend deleting them here and revisiting this commit when they are needed.
If they aren't needed for the future, these should definitely be deleted

2019-06-14 10:56 UTC, Alistair-McGann-Tessella commented on cp2800Sup/cp2800.db
> +record(mbbiDirect, "$(P)CMDRSP")
Some of your PV names are very short, I feel this makes them less intuitive to read. Is it possible to expand on these names? Particularly CMDRSP, CLRRSP and RSP.

2019-06-14 10:56 UTC, Alistair-McGann-Tessella commented on cp2800Sup/cp2800.db
> +    field(SCAN, "10 second")
Do we expect the ID of the device to change? If not, can this field be removed

2019-06-14 10:56 UTC, Alistair-McGann-Tessella commented on cp2800Sup/cp2800.proto
> +
These protocols are very complicated. Some rough documentation about what they do any why would be useful to have in the protocol file.
More fleshed out documentation should be on the wiki

2019-09-09 08:31 UTC, ChrisColeExpControl commented on cp2800Sup/cp2800.proto
> +
Unfortunately this code wasn't written by us, and no documentation for it is aviable.

2019-09-09 08:43 UTC, kjwoodsISIS commented on cp2800Sup/cp2800.proto
> +
The fundamental lesson of the HIFI Cryomag project is that undocumented code & systems come back to bite us in a big way.  Do we really want to be adding undocumented IOCs to our code base?  
Can we track down the original author?  Judging from  Liam's initial comments this IOC appears to have come from the MICE project.  The MICE project is (for now) based at ISIS, so the author might still be available to us.

2019-09-16 10:05 UTC, LiamPanchaud commented on cp2800Sup/cp2800.proto
> +
I'm reasonably confident that there is a document in the manuals folder (I can't remember the name) which documents how the CP2800 comms protocol works. It's essentially a dictionary of variables that can be referenced with hash keys. To read from one, it's prepended with 'c', to write I _think_ it's prepended with 'a'. 

e.g. reading high side pressure is 'c' to read, `0x7E 0x90` which is the hash key for the high side pressure member of the  dictionary, then followed by a `0`, but I can't remember what that does anymore.

2019-09-19 12:17 UTC, Alistair-McGann-Tessella commented on cp2800Sup/cp2800.proto
> +
Thanks Liam and Chris, I'm now happy that the wiki page and the manual on the share document the comms protocol. I've added a note in the protocol file as a signpost for these.

2019-09-19 12:20 UTC, Alistair-McGann-Tessella approved these changes

2019-09-19 12:25 UTC, merged